#!/usr/bin/env python3
#
#    Copyright (C) 2017 Simon Naunton
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Based on code from this post https://stackoverflow.com/a/17105259

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, GObject, Pango
from argparse import ArgumentParser, ArgumentTypeError, PARSER
from fcntl import fcntl, F_GETFL, F_SETFL
from os import O_NONBLOCK
from subprocess import Popen, PIPE, STDOUT
from sys import exit, stdout

def exit_code_validate(code):
    try:
        i = int(code)
        if i < 0 or i > 255:
            i = 255
    except:
        i = 255
        pass
    return i

def textview_changed(self, args):
    adj = self.get_vadjustment()
    adj.set_value(adj.get_upper() - adj.get_page_size())

def non_block_read(output):
    fd = output.fileno()
    fl = fcntl(fd, F_GETFL)
    fcntl(fd, F_SETFL, fl | O_NONBLOCK)
    try:
        return output.read()
    except:
        return ''

def update_terminal():
    b = non_block_read(sub_proc.stdout)
    if b is not None:
        s = b.decode('utf8')
        textview.get_buffer().insert_at_cursor(s)
        if args.print:
        	stdout.write(s)

    rc = sub_proc.poll()
    if rc is not None:
        exit_code[0] = rc
        if args.close:
                Gtk.main_quit()
        btn_cancel.set_visible(False)
        btn_ok.set_visible(True)
        return False
    return True

parser = ArgumentParser(description='Execute a command and display output in a gtk scrolling window',
    epilog='Returns the exit code of command executed (unless -0/--zero is specified, or -x/--exit-code is specified and user cancels)')
# Added -0/--zero because External Application Button firefox extension doesn't like return codes != 0
parser.add_argument('-0', '--zero', action='store_true', help='always return exit code 0')
parser.add_argument('-c', '--close', action='store_true', help='close immediately after command has finished executing')
parser.add_argument('-d', '--dir', help='set the working directory')
parser.add_argument('-e', '--stderr', action='store_true', help='display stderr also')
parser.add_argument('-p', '--print', action='store_true', help='echo command output to stdout')
parser.add_argument('-x', '--exit-code', type=exit_code_validate, help='return this exit code if user cancels', metavar='0-255')
parser.add_argument('-wi', '--window-icon', help='set window icon', metavar='FILE')
parser.add_argument('-wt', '--window-title', help='set the window title', metavar='TITLE')
parser.add_argument('-wx', '--window-width', type=int, default=640, help='set window width in pixels', metavar='PX')
parser.add_argument('-wy', '--window-height', type=int, default=360, help='set window height in pixels', metavar='PX')
parser.add_argument('cmd', nargs=PARSER, help='the command line to execute', metavar='COMMAND_LINE')
args = parser.parse_args()

wnd = Gtk.Window()
if args.window_title is not None:
    wnd.set_title(args.window_title)
if args.window_icon is not None:
    try:
        wnd.set_icon_from_file(args.window_icon)
    except:
        pass
wnd.set_default_size(args.window_width, args.window_height)
wnd.connect('destroy', Gtk.main_quit)

vbox = Gtk.VBox()
wnd.add(vbox)

scroll = Gtk.ScrolledWindow()
textview = Gtk.TextView()
textview.connect('size-allocate', textview_changed)
fontdesc = Pango.FontDescription('monospace')
textview.modify_font(fontdesc)
scroll.add(textview)
vbox.pack_start(scroll, True, True, 0)

bbox = Gtk.HButtonBox()
bbox.set_layout(Gtk.ButtonBoxStyle.END)
btn_ok = Gtk.Button(stock = Gtk.STOCK_OK)
btn_ok.connect('pressed', Gtk.main_quit)
btn_cancel = Gtk.Button(stock = Gtk.STOCK_CANCEL)
btn_cancel.connect('pressed', Gtk.main_quit)
bbox.add(btn_ok)
bbox.add(btn_cancel)
vbox.pack_end(bbox, False, False, 0)

wnd.show_all()
btn_ok.set_visible(False)

cwd = '.' if args.dir is None else args.dir
se = STDOUT if args.stderr is True else None
sub_proc = Popen(' '.join(args.cmd), stdout=PIPE, stderr=se, shell=True, cwd=cwd)
sub_outp = ""

# Using list for exit_code because integer variables do not seem to work as globals...?
exit_code = []
exit_code.append(0 if args.exit_code is None else int(args.exit_code))

GObject.timeout_add(100, update_terminal)
Gtk.main()

exit(0 if args.zero else exit_code[0])
